version: "3.8"
services:
  mysql_db:
    image: mysql:8.0.26
    restart: always
    security_opt:
      - seccomp:unconfined
    ports: 
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password  
  mongo_db:
    image: mongo:4.2.15
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    